apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: whispering-rhinoceros-go 
  janus-idp.io/tekton: whispering-rhinoceros-go
  backstage.io/kubernetes-id: whispering-rhinoceros-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: whispering-rhinoceros-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  