apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whispering-rhinoceros-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whispering-rhinoceros-go 
  name: whispering-rhinoceros-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: whispering-rhinoceros-go 
